import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/Navbar.jsx";
import Footer from "@/components/common/Footer.jsx";

const futura = localFont({
  src: "./fonts/futura-lt-w01-book.woff2",
  display: "swap",
});

export const metadata = {
  title: "FinlyticsHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased ${futura.className}`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}